#!/bin/bash
cd "$(dirname "$0")/.."
docker buildx build \
	--build-arg BUILDKIT_INLINE_CACHE=1 \
	--build-arg BUILD_ID="${JENKINS_BUILD_ID}" \
	--build-arg BUILD_VERSION="${FASTMCP_OPENAPI_BUILD_TAG}" \
    --file ./docker/Dockerfile \
    --load \
    --network=host \
    --tag fastmcp-openapi .
